- name: Deploy Node.js Application with Supervisor and Nginx
  hosts: webserver
  become: yes
  tasks:
    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name:
          - curl
          - gnupg
          - lsb-release
          - git
        state: present

    - name: Install Node.js (16.x)
      shell: |
        curl -sL https://deb.nodesource.com/setup_16.x | bash -
        apt install -y nodejs
      args:
        creates: /usr/bin/node

    - name: Install Supervisor
      apt:
        name: supervisor
        state: present

    - name: Ensure Supervisor is started and enabled
      service:
        name: supervisor
        state: started
        enabled: yes

    - name: Remove existing application directory
      file:
        path: /var/www/html
        state: absent

    - name: Clone Node.js application from GitHub
      git:
        repo: 'https://github.com/abhishekkewat1/devops.git'
        dest: /var/www/html
        version: code

    - name: Install Node.js dependencies (npm install)
      npm:
        path: /var/www/html
        state: present

    - name: Create Supervisor configuration for Node.js app
      copy:
        dest: /etc/supervisor/conf.d/nodeapp.conf
        content: |
          [program:nodeapp]
          command=node /var/www/html/app.js
          directory=/var/www/html
          autostart=true
          autorestart=true
          stderr_logfile=/var/log/nodeapp.err.log
          stdout_logfile=/var/log/nodeapp.out.log
          user=ubuntu
          environment=NODE_ENV=production

    - name: Reload Supervisor configuration
      shell: |
        supervisorctl reread
        supervisorctl update

    - name: Start Node.js application with Supervisor
      shell: |
        supervisorctl start nodeapp

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Disable the default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Ensure the custom Node.js Nginx configuration is enabled
      file:
        src: /etc/nginx/sites-available/nodeapp
        dest: /etc/nginx/sites-enabled/nodeapp
        state: link

    - name: Create Nginx reverse proxy configuration for Node.js app
      template:
        src: nginx_reverse_proxy.conf.j2
        dest: /etc/nginx/sites-available/nodeapp
      notify:
        - Reload Nginx

    - name: Test Nginx configuration
      command: nginx -t
      notify:
        - Reload Nginx

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
